'use client';
import dynamic from 'next/dynamic'; import {useEffect,useState} from 'react';
const Universe=dynamic(()=>import('../components/Universe'),{ssr:false});
type Obj={id:string;name:string;type:string;distance?:string;status:string;description?:string;ra?:number;dec?:number;source:string;sourceUrl?:string;image?:string;metadata?:Record<string,string|number|null>};
const featured:Obj[]=[{id:'sun',name:'Sun',type:'STAR',distance:'1 AU',status:'CONFIRMED',description:'The star at the center of the Solar System.',source:'Curated Solar System reference'},{id:'earth',name:'Earth',type:'PLANET',distance:'1 AU from Sun',status:'CONFIRMED',description:'The third planet from the Sun.',source:'Curated Solar System reference'},{id:'m31',name:'Andromeda Galaxy',type:'GALAXY',distance:'~2.5 million ly',status:'CATALOGUED',description:'A large spiral galaxy in the Local Group.',source:'SIMBAD / CDS'},{id:'m87',name:'M87*',type:'BLACK HOLE',distance:'~55 million ly',status:'INDIRECT DETECTION',description:'The supermassive black hole in M87.',source:'EHT / scientific literature'}];
export default function Home(){const[q,setQ]=useState('');const[results,setResults]=useState<Obj[]>([]);const[obj,setObj]=useState<Obj>(featured[0]);const[images,setImages]=useState<any[]>([]);const[loading,setLoading]=useState(false);
useEffect(()=>{const t=setTimeout(async()=>{if(q.trim().length<2){setResults([]);return}setLoading(true);try{const r=await fetch('/api/search?q='+encodeURIComponent(q));const d=await r.json();setResults(d.results||[])}finally{setLoading(false)}},350);return()=>clearTimeout(t)},[q]);
useEffect(()=>{fetch('/api/images?q='+encodeURIComponent(obj.name)).then(r=>r.json()).then(d=>setImages(d.items||[])).catch(()=>setImages([]))},[obj.name]);
return <main className="atlas"><div className="top"><div className="brand">COSMIC ATLAS</div><input className="search" placeholder="Search exoplanets, stars, galaxies…" value={q} onChange={e=>setQ(e.target.value)}/><button className="mode">3D ATLAS</button></div>
{(q||loading)&&<div className="results">{loading?<div className="loading">Querying NASA Exoplanet Archive + SIMBAD…</div>:results.length?results.map(x=><div className="result" key={x.id} onClick={()=>{setObj(x);setQ('')}}><strong>{x.name}</strong><small>{x.type} · {x.distance||'Distance unavailable'} · {x.source}</small></div>):<div className="loading">No verified catalogue match.</div>}</div>}
<div className="canvas"><Universe/></div><aside className="panel"><div className="eyebrow">SELECTED OBJECT</div><h1>{obj.name}</h1><span className="pill">{obj.type}</span><span className="pill">{obj.status}</span><p>{obj.description}</p><div className="grid"><div className="stat"><b>{obj.distance||'Data unavailable'}</b><span>Distance</span></div><div className="stat"><b>{obj.ra??'Data unavailable'}</b><span>Right ascension</span></div><div className="stat"><b>{obj.dec??'Data unavailable'}</b><span>Declination</span></div><div className="stat"><b>{obj.metadata?.discovery_year??'Data unavailable'}</b><span>Discovery year</span></div></div>
{obj.metadata&&<div className="meta">{Object.entries(obj.metadata).map(([k,v])=>v!==null&&v!==undefined?<div key={k}><span>{k.replaceAll('_',' ')}</span><b>{String(v)}</b></div>:null)}</div>}
<div className="source">SOURCE<br/><strong>{obj.source}</strong>{obj.sourceUrl&&<><br/><a href={obj.sourceUrl} target="_blank">Open source ↗</a></>}</div>
{images[0]?.href&&<div className="imageCard"><img src={images[0].href} alt={images[0].title}/><small>NASA Image and Video Library · observational/media archive. Verify image type in source metadata.</small></div>}
<p className="notice">Procedural background stars are visualization only—not individual catalogued objects. Missing measurements are shown as “Data unavailable”.</p></aside><div className="bottom"><div className="scale">LOGARITHMIC EXPLORATION · Solar System → stars → galaxies</div><div className="hint">Drag · scroll · search real catalogues</div></div></main>}
